In [55]:
import pandas as pd

In [56]:
DATA_PATH = "weatherAUS.csv"

In [57]:
data = pd.read_csv(DATA_PATH,parse_dates=["Date"])

In [58]:
data.head(5)

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,2008-12-01,Albury,13.4,22.9,0.6,NaN,NaN,W,44.0,W,...,71.0,22.0,1007.7,1007.1,8.0,NaN,16.9,21.8,No,No
1,2008-12-02,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44.0,NNW,...,44.0,25.0,1010.6,1007.8,NaN,NaN,17.2,24.3,No,No
2,2008-12-03,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0,W,...,38.0,30.0,1007.6,1008.7,NaN,2.0,21.0,23.2,No,No
3,2008-12-04,Albury,9.2,28.0,0.0,NaN,NaN,NE,24.0,SE,...,45.0,16.0,1017.6,1012.8,NaN,NaN,18.1,26.5,No,No
4,2008-12-05,Albury,17.5,32.3,1.0,NaN,NaN,W,41.0,ENE,...,82.0,33.0,1010.8,1006.0,7.0,8.0,17.8,29.7,No,No

In [59]:
data.dtypes

Date             datetime64[us]
Location                    str
MinTemp                 float64
MaxTemp                 float64
Rainfall                float64
Evaporation             float64
Sunshine                float64
WindGustDir                 str
WindGustSpeed           float64
WindDir9am                  str
WindDir3pm                  str
WindSpeed9am            float64
WindSpeed3pm            float64
Humidity9am             float64
Humidity3pm             float64
Pressure9am             float64
Pressure3pm             float64
Cloud9am                float64
Cloud3pm                float64
Temp9am                 float64
Temp3pm                 float64
RainToday                   str
RainTomorrow                str
dtype: object

In [60]:
data["Location"].value_counts()

Location
Canberra            3436
Sydney              3344
Melbourne           3193
Brisbane            3193
Adelaide            3193
Perth               3193
Hobart              3193
Darwin              3193
Albury              3040
Wollongong          3040
MountGinini         3040
Ballarat            3040
Bendigo             3040
Cairns              3040
GoldCoast           3040
Townsville          3040
MountGambier        3040
Albany              3040
Launceston          3040
AliceSprings        3040
Newcastle           3039
Penrith             3039
Tuggeranong         3039
BadgerysCreek       3009
Cobar               3009
CoffsHarbour        3009
Moree               3009
NorfolkIsland       3009
Richmond            3009
SydneyAirport       3009
WaggaWagga          3009
Williamtown         3009
Sale                3009
MelbourneAirport    3009
Mildura             3009
Portland            3009
Watsonia            3009
Dartmoor            3009
Nuriootpa           3009
Woomera             3009
Witchcliffe         3009
PearceRAAF          3009
PerthAirport        3009
Walpole             3006
NorahHead           3004
SalmonGums          3001
Nhil                1578
Katherine           1578
Uluru               1578
Name: count, dtype: int64

In [61]:
data_melb_airport = data.loc[data["Location"]=="MelbourneAirport",["Date","MaxTemp"]]

In [62]:
data_melb_airport = (
    data_melb_airport
    .sort_values("Date")
    .reset_index(drop=True)
)

In [63]:
data_melb_airport.head(5)

        Date  MaxTemp
0 2009-01-01     19.9
1 2009-01-02     17.8
2 2009-01-03     21.1
3 2009-01-04     29.2
4 2009-01-05     29.0

In [64]:
data_melb_airport.shape

(3009, 2)

In [65]:
data_melb_airport.describe()

                             Date      MaxTemp
count                        3009  3009.000000
mean   2013-04-07 02:02:30.747756    20.491858
min           2009-01-01 00:00:00     8.400000
25%           2011-01-23 00:00:00    15.300000
50%           2013-05-13 00:00:00    19.100000
75%           2015-06-04 00:00:00    24.500000
max           2017-06-25 00:00:00    46.800000
std                           NaN     6.653313

In [66]:
data_melb_airport.info()

<class 'pandas.DataFrame'>
RangeIndex: 3009 entries, 0 to 3008
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Date     3009 non-null   datetime64[us]
 1   MaxTemp  3009 non-null   float64
dtypes: datetime64[us](1), float64(1)
memory usage: 47.1 KB

In [67]:
data_melb_airport.isna().sum()

Date       0
MaxTemp    0
dtype: int64

In [68]:
print(
    "Duplicate dates:",
    data_melb_airport["Date"].duplicated().sum()
)

expected_dates = pd.date_range(
    start=data_melb_airport["Date"].min(),
    end=data_melb_airport["Date"].max(),
    freq="D"
)

missing_dates = expected_dates.difference(
    data_melb_airport["Date"]
)

print("Missing calendar dates:", len(missing_dates))
print(missing_dates)

Duplicate dates: 0
Missing calendar dates: 89
DatetimeIndex(['2011-04-01', '2011-04-02', '2011-04-03', '2011-04-04',
               '2011-04-05', '2011-04-06', '2011-04-07', '2011-04-08',
               '2011-04-09', '2011-04-10', '2011-04-11', '2011-04-12',
               '2011-04-13', '2011-04-14', '2011-04-15', '2011-04-16',
               '2011-04-17', '2011-04-18', '2011-04-19', '2011-04-20',
               '2011-04-21', '2011-04-22', '2011-04-23', '2011-04-24',
               '2011-04-25', '2011-04-26', '2011-04-27', '2011-04-28',
               '2011-04-29', '2011-04-30', '2012-12-01', '2012-12-02',
               '2012-12-03', '2012-12-04', '2012-12-05', '2012-12-06',
               '2012-12-07', '2012-12-08', '2012-12-09', '2012-12-10',
               '2012-12-11', '2012-12-12', '2012-12-13', '2012-12-14',
               '2012-12-15', '2012-12-16', '2012-12-17', '2012-12-18',
               '2012-12-19', '2012-12-20', '2012-12-21', '2012-12-22',
               '2012-12-23', '2012-12-24', '2012-12-25', '2012-12-26',
               '2012-12-27', '2012-12-28', '2012-12-29', '2012-12-30',
               '2012-12-31', '2013-02-01', '2013-02-02', '2013-02-03',
               '2013-02-04', '2013-02-05', '2013-02-06', '2013-02-07',
               '2013-02-08', '2013-02-09', '2013-02-10', '2013-02-11',
               '2013-02-12', '2013-02-13', '2013-02-14', '2013-02-15',
               '2013-02-16', '2013-02-17', '2013-02-18', '2013-02-19',
               '2013-02-20', '2013-02-21', '2013-02-22', '2013-02-23',
               '2013-02-24', '2013-02-25', '2013-02-26', '2013-02-27',
               '2013-02-28'],
              dtype='datetime64[us]', freq=None)

In [69]:
data_melb_airport = (
    data_melb_airport
    .set_index("Date")
    .asfreq("D")
)